name: Construction et déploiement de la configuration

on:
  push:
    branches:
      - ci/documentation

permissions:
  contents: read
  pages: write
  id-token: write  # Nécessaire pour déployer sur GitHub Pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Positionnement sur le dépôt
        uses: actions/checkout@v4

      - name: Mis en place de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
          pip install sphinx_rtd_theme --break-system-packages

      - name: Construction de la documentation (avec Sphinx)
        run: |
          sphinx-build -b html docs/source docs/build/html

      - name: Publication la documentation générée
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html  # Dossier contenant la doc générée

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4